export const featuredPets = [
  {
    id: "p1",
    name: "Luna",
    species: "Dog",
    breed: "Golden Retriever",
    age: 2,
    gender: "Female",
    image:
      "https://images.unsplash.com/photo-1507146426996-ef05306b995a?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Dhanmondi, Dhaka",
    fee: 120,
    description:
      "Playful and gentle, Luna loves kids and is great on leash walks.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p2",
    name: "Milo",
    species: "Cat",
    breed: "British Shorthair",
    age: 3,
    gender: "Male",
    image:
      "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Banani, Dhaka",
    fee: 90,
    description:
      "Calm, curious, and loves sunny spots by the window.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p3",
    name: "Kiwi",
    species: "Bird",
    breed: "Parakeet",
    age: 1,
    gender: "Female",
    image:
      "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Not required",
    location: "Gulshan, Dhaka",
    fee: 45,
    description:
      "Bright, vocal, and friendly with daily interaction.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p4",
    name: "Hazel",
    species: "Rabbit",
    breed: "Holland Lop",
    age: 2,
    gender: "Female",
    image:
      "https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Uttara, Dhaka",
    fee: 60,
    description:
      "Sweet and calm, Hazel enjoys gentle pets and quiet spaces.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p5",
    name: "Rocket",
    species: "Dog",
    breed: "Border Collie",
    age: 4,
    gender: "Male",
    image:
      "https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Mirpur, Dhaka",
    fee: 150,
    description:
      "High energy and super smart, perfect for active families.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p6",
    name: "Misty",
    species: "Cat",
    breed: "Siamese",
    age: 1,
    gender: "Female",
    image:
      "https://images.unsplash.com/photo-1543852786-1cf6624b9987?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Bashundhara, Dhaka",
    fee: 95,
    description:
      "Affectionate and chatty, Misty bonds quickly with people.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p7",
    name: "Oliver",
    species: "Dog",
    breed: "Beagle",
    age: 5,
    gender: "Male",
    image:
      "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Mohakhali, Dhaka",
    fee: 110,
    description:
      "Friendly with everyone, great for first-time dog parents.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
  {
    id: "p8",
    name: "Clover",
    species: "Rabbit",
    breed: "Dutch",
    age: 3,
    gender: "Male",
    image:
      "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?q=80&w=900&auto=format&fit=crop",
    healthStatus: "Healthy",
    vaccinationStatus: "Up to date",
    location: "Farmgate, Dhaka",
    fee: 55,
    description:
      "Easygoing and gentle, loves leafy greens and calm cuddles.",
    ownerEmail: "shelter@pawhaven.com",
    ownerName: "Paw Haven",
    status: "available",
  },
];

export const speciesOptions = ["Dog", "Cat", "Bird", "Rabbit", "Other"];
